version: "3.1"

services:
  web:
    build: ./movies_admin
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 -w3
    container_name: django_web
    volumes:
      - static_volume:/usr/src/web/config/static
      - media_volume:/usr/src/web/media
    networks:
      - dotnetwork
    env_file:
      - ./movies_admin/config/settings/.env
    depends_on:
      - db

  db:
    image: postgres
    networks:
      - dotnetwork
    volumes:
      - ./schema_design/init.sql:/docker-entrypoint-initdb.d/init_schema.sql
      - postgres_data:/var/lib/postgresql/data/
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=jaqombo
      - POSTGRES_DB=movies

  sqlite_to_postgres:
    build: ./sqlite_to_postgres
    container_name: sqlite_to_postgres
    env_file:
      - ./sqlite_to_postgres/.env
    depends_on:
      - db
    networks:
      - dotnetwork
    command: python load_data.py

  postgres_to_es:
    build: ./postgres_to_es
    container_name: postgres_to_es
    env_file:
      - ./postgres_to_es/.env
    depends_on:
      - elasticsearch
      - sqlite_to_postgres
    networks:
      - dotnetwork
    command: python main.py

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elastic
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - web
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - dotnetwork

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    networks:
      - dotnetwork
    links:
      - elasticsearch

  redis_db:
    image: redis:alpine
    container_name: redis_db
    networks:
      - dotnetwork

  nginx:
    build: ./nginx
    container_name: ngx
    volumes:
      - static_volume:/usr/src/web/config/static
      - media_volume:/usr/src/web/media
    ports:
      - 1337:80
      - 8881:8881
      - 8882:8882
    networks:
      - dotnetwork
    depends_on:
      - elasticsearch
      - kibana
      - web
    restart: always

networks:
  dotnetwork:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
  esdata:
